### ISSUE TITLE
target_clangformat_setup() usage in project with multiple targets

### ISSUE THREAD

**Issue by wrightsg** [zemasoft/clangformat-cmake#2]
As far as I can tell it is not possible to use this CMake module in projects with hierarchical `CMakeLists.txt` and/or multiple CMake targets.

Assuming project with an exectuable and library target it would be nice to be able to use the CMake module as follows.

```
project(my_app)

list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/clangformat-cmake/cmake)
include(ClangFormat)

add_library(my_lib my_lib.cpp)
target_clangformat_setup(my_lib)

add_executable(my_app my_app.cpp)
target_clangformat_setup(my_app)
target_link_libraries(my_app my_lib)
```

However this will currently fail because each call to `target_clangformat_setup()` results in a call to `add_custom_target()` with the same target name (`${PROJECT_NAME}_clangformat`).

A possible workaround would be to use `clangformat_setup()` directly. However, this would require to list all source files twice and does not work with hierarchical CMakeLists.txt setups: assuming you have a separate CMakeLists.txt for the executable and the library from the above example.

`CMakeLists.txt` for executable 

```
project(my_app)

list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/clangformat-cmake/cmake)
include(ClangFormat)

add_subdirectory(lib)

add_executable(my_app my_app.cpp)
clangformat_setup(my_app.cpp)
target_link_libraries(my_app my_lib)
```

`CMakeLists.txt` for library

```
add_library(my_lib my_lib.cpp)
clangformat_setup(my_lib.cpp)
```

This will also fail because `clangformat_setup()` is called twice in the same project.

edit: I have just discovered your example repository that demonstrates usage of the CMake module. In the example, the problem is avoided by having separate `project()` command in the main and test `CMakeLists.txt`. Is this a CMake pattern when using hierarchical `CMakeLists.txt`? However, this will still fail if multiple targets are defined in the same `CMakeLists.txt` file.

**Comment by zemasoft** [comment]
Hi wrightsg,

thank you for your input and sorry for my late response.

You are very right. The scenario you have described will break when `PROJECT_NAME` is used as a part of the target name and I was forced to workaround that by adding `project()` into the nested `CMakeLists.txt` in the example and that is definitely not the right way of doing things in CMake.

I could not adopt your solution as I wanted to preserve the possibility to just:

```
clangformat_setup(
  src/hello.cpp
  src/hello.hpp
)
```

But other than that, the current solution is quite similar to yours.

NOTE: The current solution is not working for alias targets anymore.
